### ISSUE TITLE
Examples initially load with black screen

### ISSUE THREAD

**Issue by Shootertrex** [redox-os/orbtk#110]
**Describe the bug**
When running any of the examples, the window will load as a black screen until clicking into it. Clicking into the `image` example does not display the image though, so it may be related to an animation or something.

**To Reproduce**
1. run `cargo run --release --example calculator`
2. window is black
3. click anywhere in the window
4. calculator elements now appear

**Expected behavior**
Window elements should be loaded initially.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Rust version: 1.39
 - Orbtk version: master (hash 40d28c8)

**Comment by FloVanGH** [comment]
@Shootertrex thank you for your report. What desktop environment do you?

**Comment by Shootertrex** [comment]
I am using KDE Plasma 5.17.3

**Comment by FloVanGH** [comment]
I will check it.

**Comment by FloVanGH** [comment]
Maybe there is a working solution. I will check it and let you know.

**Comment by Light-Wizzard** [comment]
When I run the example I can see the display, if I hit the shade button, the screen comes back black, until I click in it, as described above, I am in Cinnamon, and added shade to window, I know it is mostly a KDE thing, but it seems the shade has its own event handler that you are not trapping, I think in KDE it toggles shade as an effect, giving a window an opening look, and a drop-down look when it closes and could be causing this issue.

You can reproduce this problem by setting your Window to have Shade control, in Cinnamon I use the System Settings app and Windows, I set the left side title bar button to Shade, it will show an up arrow in the left corner, clicking on it will collapse the window into the title bar, so you can see under it, clicking on it again restores the window.

When it opens the screen is black until you click on it. 

If I set effects, I can also get this black screen on start, just like above, which leads me to believe this is the problem, otherwise, this is another issue. 

I hope this helps.

**Comment by s0kil** [comment]
Experiencing the same problem on Ubuntu 19.10

**Comment by FloVanGH** [comment]
At the moment we have a collection of bugs related to minfb. The developer of minifb is working on that bugs. But I will implement an experimental winit based window backend soon. Maybe that could be solve this problems too.
