### ISSUE TITLE
Z-Axis

### ISSUE THREAD

**Issue by FloVanGH** [redox-os/orbtk#122]
# Context

To create widgets like menus, drop downs and dialogs it should be possible to stack widgets on z axis without to respect the position of the widget in the tree.

# Problem description & Solution

Implement an z position property for all widgets. Widgets with a greater z index are rendered over the widgets with lower z index. The event system should also respect the given z position property.

**Comment by valkum** [comment]
Isn't the way flutter handles that a better solution? 
See [PopupMenuButton's](https://api.flutter.dev/flutter/material/PopupMenuButton-class.html) use of [Overlay](https://api.flutter.dev/flutter/widgets/Overlay-class.html)

**Comment by FloVanGH** [comment]
@valkum thank you for the hint. Looks like a good solution. I will check it in detail.

My thought was something like this:

```rust
Grid::create()
    // Add the child to the main tree (main layer)
    .child(Button::create().text("Button).build(ctx))
   // Adds the child to layer 10. If layer does not exists it will created
   .z_layer(10, TextBlock::create().text("Layer 10").build(ctx))
```

**Comment by valkum** [comment]
The problem with that is, it breaks the basic assumption that z goes up when descending into the tree.
What if you want to use multiple widgets that set a z-index? They can't be hardcoded and you have to do z-axis layouting manually. Otherwise you could have basic widgets drawn behind something.
Having a widget early in the tree that basically delegates the order in the z axis seems to be the better solution. 
You would pass you widget to that delegation widget which could also take a visibility importance flag. E.g.
```Order {
Background,
Z(u8),
Front
}```

I might be biased as I only worked with Flutter and not Yew but I think this way has advantages.

**Comment by FloVanGH** [comment]
You're right. I've checked the flutter documentation and it is a better way. I will add something similar to OrbTk. Thank you.
