### ISSUE TITLE
vanilla orbtk template panics

### ISSUE THREAD

**Issue by Tazoeur** [redox-os/orbtk#184]
Hello,

First of all I'd like to thank you for the work you are doing, it looked soo nice and clean I wanted to try/use it.

So I've followed the orbtk-template procedure
```
cargo generate --git https://github.com/redox-os/orbtk-template.git --name my-project
cd my-project
cargo build
cargo run
```

and I got this error  :
```
thread 'main' panicked at 'Failed to create window "XOpenDisplay failed"', /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:16:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Here is the orbtk version in my cargo.lock file
```
[[package]]
name = "orbtk"
version = "0.3.1-alpha2"
source = "git+https://github.com/redox-os/orbtk.git?branch=develop#df45cc7d1b66a1a6cea588febaddc16c8697355e"
dependencies = [
 "dces",
 "orbtk-api",
 "orbtk-css-engine",
 "orbtk-proc-macros",
 "orbtk-render",
 "orbtk-shell",
 "orbtk-theme",
 "orbtk-tree",
 "orbtk-utils",
 "orbtk-widgets",
]
```

I've just updated rust nightly 
```
$ rustc --version
rustc 1.44.0-nightly (94d346360 2020-04-09)
```
I do have `libsdl2-dev` installed.

I run a Ubuntu 19.10 (5.3.0-46-generic)  x86_64 with gnome 3.34.2 

I hope this is me being stupid but I did not see anyone else having the same problem as me so I took the liberty to submit this issue.

**Comment by FloVanGH** [comment]
I could not reproduce it on `macos` but I will check it on my Ubuntu machine today. `ibsdl2-dev` should not be necessary.

**Comment by slothyrulez** [comment]
Tested right now on ubuntu 20.04
```
cargo generate --git https://github.com/redox-os/orbtk-template.git --name my-project
cd my-project
cargo build
cargo run
```

Orbtk on Cargo.lock

```
[[package]]
name = "orbtk"
version = "0.3.1-alpha3"
source = "git+https://github.com/redox-os/orbtk.git?branch=develop#463c110e1ab43423278c9567f88fc044ce3442bf"
dependencies = [
 "dces",
 "orbtk-api",
 "orbtk-css-engine",
 "orbtk-proc-macros",
 "orbtk-render",
 "orbtk-shell",
 "orbtk-theme",
 "orbtk-tree",
 "orbtk-utils",
 "orbtk-widgets",
]
```

Running on wayland

Btw, i don't know ohw this black magic works, but I can't find `version = "0.3.1-alpha3"` on crates.io or the orbtk's github repo.

**Comment by Tazoeur** [comment]
yup just did that too and its working...

I guess it wasn't a good time to test it back then :'(

I'll give it a go in the near future :)

**Comment by kivimango** [comment]
Can you test it again pls?
Can we close it ?

**Comment by Tazoeur** [comment]
yup, working as expected since last time (5 may)

**Comment by kivimango** [comment]
thank you.

**Comment by shadiakiki1986** [comment]
My 2 cents:
- if I ssh into ubuntu server 20.04, launch a `screen` session, and try to build the minimal example on the README, then I get the same `Failed to create window "XOpenDisplay failed"`. This panic would make sense because there is no GUI at this stage
- if I use Remmina to connect to the desktop gui via RDP, launch a terminal, attach to the earlier ssh screen session with `screen -rd`, run the same minimal example, it still gives the same panic, despite now having a GUI
- if I launch another terminal, create a new `screen` session, and build the minimal example, it works

Comparing the two sessions, I notice difference in the environment variables. Most notably, the session that runs it fine has variables not in the session that panics: `DESKTOP_SESSION=LXDE, DISPLAY=:10.0, QT_ACCESSIBILITY=1, TERMCAP=SC|screen.xterm...`

Then I simply set the environment variable `DISPLAY=:10.0` in the session that panicked, and it worked.

**Comment by shadiakiki1986** [comment]
Btw, fun fact: building the minimal example with `DISPLAY=:10.0` from a terminal via ssh (no GUI) would display the window in the session via remote desktop (RDP). I found that convenient for testing since I can develop in the ssh terminal outside Remmina (remote desktop client) on one side of my screen, and then view the build GUI in Remmina on the other side of my screen.
