### ISSUE TITLE
[Question] comparison with other Rust GUI Toolkits

### ISSUE THREAD

**Issue by ngortheone** [redox-os/orbtk#210]
Hello @FloVanGH and team,

Could you briefly compare the ideological and design aspects of orbtk to other popular Rust GUI toolkits?

In particular 
- https://github.com/hecrj/iced and its Elm-inspired design

Also if you can: 
- https://github.com/PistonDevelopers/conrod
- Azul
- Druid

Thanks!

**Comment by FloVanGH** [comment]
Hello @ngortheone,

I think the many difference to the other toolkits in your list, is that OrbTk is complete based on an Entity Component System. The widgets are entities (indies) and the properties (members) of a widget are components in a map. You could compare it to the Amethyst game engine. But the access to the Entity Component System is abstracted. You will access widgets and properties in a more familiar way. 
On the side there is a little inspiration of React or Elm, but just a little bit on the api.

What is also different to the most other toolkits, is that a `State` does not store the inner state of a widget, it only give you access to the widget and let you manipulate it.

It hope this is the information you are seeking.

**Comment by ngortheone** [comment]
Thanks for your reply

> It hope this is the information you are seeking

I am infrastructure / backend engineer and I am quite far from UI, but still generally curious. I have more newbie-like question like:

- why is Entity Component System was chosen and why do you believe it better then other solutions?
- is there an layman's example like "you can do X, which you can't do with other toolkits"


Basically the meta question is - how would you sell it to a technician, whose main area of knowledge is not UI?

**Comment by FloVanGH** [comment]
> why is Entity Component System was chosen and why do you believe it better then other solutions?

I first approach was very classic OOP. Each widget derives from a specific trait but I has to copy / paste all properties for each new widget such as bounds, constraints, background, ... . And I have to apply all changes manually to all widgets. On my search for an other solution I found the ECS and it is very popular on game dev and I gave it a try also on a GUI toolkit. And I'm totally flexible and fast. e.g you could very easy attach new properties to widgets. It is also possible on runtime. From development side I think that is definitely a advantage.

> is there a layman's example like "you can do X with OrbTk, and you can't do it (or is very hard to do) with other toolkits"?

I think it could be the customization of widgets and the creation of new widgets.

> Basically the meta question is - how would you sell it to a technician, whose main area of knowledge is not UI?

I think what we need here, are descriptive examples, a very good documentation and a very good startup guide. This are major topics of the 0.3 release.

 >This reminds me of arena-based approach used to encode trees. Does this play nicely with Rust ownership system? AFAIK arena-based approach suffers from the fact that it basically opts-out of rust ownership tracking allowing you to introduce bugs.

It works very fine with the owenership, I also request data on the time I need it. On my first approach I ended up using Rc and RefCell a lot.

> What problem does this solve?

The intention was not to do it unlike the others, but because all widget data is stored in the ecs it was the best solution.
