### ISSUE TITLE
Examples fail to run

### ISSUE THREAD

**Issue by nebrelbug** [redox-os/orbtk#264]
**Describe the bug**

When running `cargo run --example widgets --release`, the build fails with

```
error: failed to run custom build command for `xkbcommon-sys v0.7.4`
...
Caused by:
  process didn't exit successfully: `/home/nebrelbug/Coding/orbtk-tests/orbtk/target/release/build/xkbcommon-sys-6ca975e3b9f6478a/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=XKBCOMMON_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
...
```

**To Reproduce**
1. Clone the OrbTK repository
2. Run `cargo run --example widgets --release` inside the repository

**Expected behavior**
Examples would run.

**Screenshots**

**Desktop (please complete the following information):**
 - Pop!_OS 20.04

**Additional context**
Problem occurs when using nightly or stable Rust.

**Comment by FloVanGH** [comment]
You first need to install

```sudo apt install libxkbcommon-dev libwayland-cursor0 libwayland-dev```

**Comment by FloVanGH** [comment]
Does is worked?

**Comment by FloVanGH** [comment]
I close this now if you have still that issue you could reopen it.

**Comment by nebrelbug** [comment]
This fixed it! Is this anywhere in the docs? Might be helpful for other users.

**Comment by kivimango** [comment]
It's in the README

**Comment by nebrelbug** [comment]
@kivimango oops, don't know how I missed that. Thanks!

Are those packages required in order to run OrbTK in general?

**Comment by kivimango** [comment]
I'm not sure, I would say yes, I'm on win 10 currently.

**Comment by darkcharmander** [comment]
Installing the packages that @FloVanGH mentioned didn't work: they were already installed on my computer but I still have problems, 

The 'image' example doesn't work. It compiles fine but after you try to start it, you get this in the console:
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  1 (X_CreateWindow)
  Value in failed request:  0x0
  Serial number of failed request:  85
  Current serial number in output stream:  92
```
Other examples like e.g. the calculator do work fine. It 'could' be a driver issue since I am running this machine in VirtualBox.
OS: Kubuntu 20.04 x64

**Comment by shadiakiki1986** [comment]
In my case it turned out that the `pkg-config` program was not installed. Installed it with `sudo apt-get install -y pkg-config`. It turns out that there's an open issue for it in [pkg-config-rs/issues/103](https://github.com/rust-lang/pkg-config-rs/issues/103), which in its turn is used by [rust-xkbcommon-sys](https://github.com/meh/rust-xkbcommon-sys/)

**Comment by darkcharmander** [comment]
I don't know why, but I re-downloaded orbtk and recompiled everything, and the image sample works now. Disregard my previous post!
