### ISSUE TITLE
Orbtk - No Cursor

### ISSUE THREAD

**Issue by etrofla** [redox-os/orbtk#279]
**Describe the bug**
Compiled source with no errors
When executing widget example (and others) no cursor is displayed in the Orbtk windows, only outside of window.
This is displayed in the terminal on execution:
  Failed to create server-side surface decoration: Missing (nothing else after this)

Running ubuntu 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by uniformbuffer** [comment]
Hi,
what desktop environment are you using?
If using GNOME, are you running on XOrg or Wayland?

**Comment by fstephany** [comment]
I have a similar bug on Fedora 32 (vanilla Gnome+Wayland). 

- window decorations are not drawn and the window is stuck on the top left corner of the screen (cf screenshot)
- `Failed to create server-side surface decoration: Missing` is printed in the terminal


![Screenshot from 2020-08-13 17-51-55](https://user-images.githubusercontent.com/35817/90158812-ca297d80-dd8f-11ea-99f0-b231431f707a.png)

**Comment by grelltrier** [comment]
Same on Arch + Gnome + Wayland. Also in the application overview the box around the application window is not drawn correctly. I tried all the examples and all of them exceed the frame

![OrbTk](https://user-images.githubusercontent.com/67273701/90271358-387f4600-de4b-11ea-9ff9-99b2afea00af.png)

**Comment by FloVanGH** [comment]
@grelltrier could you do me a favor and check if you have the same problems on the orblient branch? If you check it one note, there the key events do not work at the moment.

**Comment by grelltrier** [comment]
Sure, with this branch I had to install cmake because sdl2-sys needed me to do so. After that was done, everything worked perfectly fine :) I get a cursor, the window is no longer popping up partially outside of my window, the window is decorated and the frame in the application overview matches.
Resizing the window unfortunately crashes it and it takes a long time to react to my input though but this is great progress, thank you!

![OrbTk](https://user-images.githubusercontent.com/67273701/90291712-02a08880-de70-11ea-853f-9a2d57746db9.png)

**Comment by FloVanGH** [comment]
@grelltrier could you also check the develop branch with `cargo run --example widgets --features pathfinder`?

**Comment by grelltrier** [comment]
I tried but I get multiple compiler warnings and when running it, it panics. Here is the backlog:

`
[user@archlnx orbtk]$ RUST_BACKTRACE=1 cargo run --example widgets --features pathfinder 
warning: unused variable: `family`
   --> crates/render/src/pathfinder/mod.rs:143:37
    |
143 |     pub fn register_font(&mut self, family: &str, font_file: &'static [u8]) {}
    |                                     ^^^^^^ help: if this is intentional, prefix it with an underscore: `_family`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `font_file`
   --> crates/render/src/pathfinder/mod.rs:143:51
    |
143 |     pub fn register_font(&mut self, family: &str, font_file: &'static [u8]) {}
    |                                                   ^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_font_file`

warning: unused variable: `x_a`
   --> crates/render/src/pathfinder/mod.rs:256:13
    |
256 |         let x_a = x as f32 * device_pixel_ratio;
    |             ^^^ help: if this is intentional, prefix it with an underscore: `_x_a`

warning: unused variable: `image`
   --> crates/render/src/pathfinder/mod.rs:294:34
    |
294 |     pub fn draw_image(&mut self, image: &Image, x: f64, y: f64) {}
    |                                  ^^^^^ help: if this is intentional, prefix it with an underscore: `_image`

warning: unused variable: `x`
   --> crates/render/src/pathfinder/mod.rs:294:49
    |
294 |     pub fn draw_image(&mut self, image: &Image, x: f64, y: f64) {}
    |                                                 ^ help: if this is intentional, prefix it with an underscore: `_x`

warning: unused variable: `y`
   --> crates/render/src/pathfinder/mod.rs:294:57
    |
294 |     pub fn draw_image(&mut self, image: &Image, x: f64, y: f64) {}
    |                                                         ^ help: if this is intentional, prefix it with an underscore: `_y`

warning: unused variable: `start`
   --> crates/render/src/pathfinder/mod.rs:357:37
    |
357 |             Brush::LinearGradient { start, end, stops } => {}
    |                                     ^^^^^ help: try ignoring the field: `start: _`

warning: unused variable: `end`
   --> crates/render/src/pathfinder/mod.rs:357:44
    |
357 |             Brush::LinearGradient { start, end, stops } => {}
    |                                            ^^^ help: try ignoring the field: `end: _`

warning: unused variable: `stops`
   --> crates/render/src/pathfinder/mod.rs:357:49
    |
357 |             Brush::LinearGradient { start, end, stops } => {}
    |                                                 ^^^^^ help: try ignoring the field: `stops: _`

warning: unused variable: `start`
   --> crates/render/src/pathfinder/mod.rs:375:37
    |
375 |             Brush::LinearGradient { start, end, stops } => {}
    |                                     ^^^^^ help: try ignoring the field: `start: _`

warning: unused variable: `end`
   --> crates/render/src/pathfinder/mod.rs:375:44
    |
375 |             Brush::LinearGradient { start, end, stops } => {}
    |                                            ^^^ help: try ignoring the field: `end: _`

warning: unused variable: `stops`
   --> crates/render/src/pathfinder/mod.rs:375:49
    |
375 |             Brush::LinearGradient { start, end, stops } => {}
    |                                                 ^^^^^ help: try ignoring the field: `stops: _`

warning: 12 warnings emitted

warning: unused import: `vec2f`
 --> crates/shell/src/glutin/window_builder.rs:9:35
  |
9 | use pathfinder_geometry::vector::{vec2f, vec2i};
  |                                   ^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused variable: `input`
  --> crates/shell/src/glutin/window.rs:72:60
   |
72 |                 event: event::WindowEvent::KeyboardInput { input, .. },
   |                                                            ^^^^^ help: if this is intentional, prefix it with an underscore: `_input`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `title`
   --> crates/shell/src/glutin/window.rs:151:48
    |
151 |                     WindowRequest::ChangeTitle(title) => {
    |                                                ^^^^^ help: if this is intentional, prefix it with an underscore: `_title`

warning: variable does not need to be mutable
   --> crates/shell/src/glutin/window_builder.rs:143:13
    |
143 |         let mut renderer = Renderer::new(
    |             ----^^^^^^^^
    |             |
    |             help: remove this `mut`
    |
    = note: `#[warn(unused_mut)]` on by default

warning: variable does not need to be mutable
   --> crates/shell/src/glutin/window_builder.rs:167:13
    |
167 |         let mut render_context = RenderContext2D::new_ex(
    |             ----^^^^^^^^^^^^^^
    |             |
    |             help: remove this `mut`

warning: 5 warnings emitted

warning: variable does not need to be mutable
  --> crates/api/src/application/mod.rs:83:16
   |
83 |     pub fn run(mut self) {
   |                ----^^^^
   |                |
   |                help: remove this `mut`
   |
   = note: `#[warn(unused_mut)]` on by default

warning: 1 warning emitted

    Finished dev [optimized + debuginfo] target(s) in 0.39s
     Running `target/debug/examples/widgets`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/wayland/window.rs:398:22
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:101
  13: core::panicking::panic
             at src/libcore/panicking.rs:56
  14: core::option::Option<T>::unwrap
             at /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/macros/mod.rs:10
  15: winit::platform_impl::platform::wayland::window::Window::current_monitor
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/wayland/window.rs:398
  16: winit::platform_impl::platform::Window::current_monitor
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:441
  17: winit::window::Window::current_monitor
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/window.rs:756
  18: orbtk_shell::platform::window_builder::WindowBuilder<A>::build
             at ./crates/shell/src/glutin/window_builder.rs:137
  19: orbtk_api::application::Application::window
             at ./crates/api/src/application/mod.rs:74
  20: widgets::main
             at examples/widgets.rs:482
  21: std::rt::lang_start::{{closure}}
             at /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  22: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  23: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  24: std::panicking::try
             at src/libstd/panicking.rs:274
  25: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  26: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  27: std::rt::lang_start
             at /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  28: main
  29: __libc_start_main
  30: _start
`

**Comment by grelltrier** [comment]
The above was when using Rust stable. When I use nightly I basically get the same result:

`thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/wayland/window.rs:398:56`

**Comment by FloVanGH** [comment]
Should be fixed with the new default backend orbraq (OrbClient and raqote).
