### ISSUE TITLE
Unresponsive / laggy

### ISSUE THREAD

**Issue by AlveLarsson** [redox-os/orbtk#291]
**Describe the bug**
I've recently tried to use OrbTK and it's quite un-responsive, 

- All Text input is slow and can't catch up when pressing multiple keys at once (compared to native)
- The slider is also unresponsive and can't catch up

I'm running this in release mode on a 1080Ti, with a 144hz monitor.
**Expected behavior**
Compared to native and web it's very unresponsive.

**Screenshots**
https://www.youtube.com/watch?v=skcRHvJaSIs&feature=youtu.be

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 2004 (19041.388)
 - OrbTK: #4c2382a (0.3.1-alpha2)

**Comment by FloVanGH** [comment]
Hi, thank you for the report. We have done a lot of performance improvements for the upcoming release 0.3.1-alpha3. Could you check if you have the same issue with the sources if the current development branch, please. The next version will be released soon.

Thank you

**Comment by AlveLarsson** [comment]
You mean on
`orbtk = { git = "https://github.com/redox-os/orbtk.git", branch= "develop" }`
as i did record the same thing on the latest commit

**Comment by FloVanGH** [comment]
I've checked your video and after I've read your description I imagined it much worse. It's still an alpha version and it's not yet optimized enough to be as fast as native frameworks. Until now the main purpose was to create a usable api and to add features. With 0.3 we've started from scratch. Until the stable release each version alpha and beta will contains performance improvements. So 0.3.1-alpha4 will contain a new backend with hardware allocated rendering. This should be also a big step from performance perspective.

Could you do me a favor and add the version to the description or topic your video. Otherwise viewers will not no that is a video from an alpha version. Thank you.

**Comment by thivmcthiv2** [comment]
It could be that you are using the debug build. I couldn't see which build you were using by the video, but I noticed that on older versions the debug build has a much worse performance.

**Comment by AlveLarsson** [comment]
@FloVanGH All ok, just letting you know, I'd love to check it out later when the new versions are out. Also, I changed the video for you so it says 0.3.1-alpha2.

@thivmcthiv2 I did use the --release tag for the video and the other tests. 

Also capturing on video that text input is slow is quite hard.

**Comment by FloVanGH** [comment]
@AlveLarsson thank you very much. I'm glade you are interested in OrbTk. I think the next performance boost will come in the next weeks with the new backend. I will let you know when it's done. 

I will close this issue because performance optimization will be a ongoing topic in the further development.
