### ISSUE TITLE
Drag/drop for files?

### ISSUE THREAD

**Issue by Autofire** [redox-os/orbtk#400]
Hi! I'm fairly new to OrbTk (and Rust?), so I'm sorry if this is a bit of a silly question.

I'm working on a project which will have a pretty basic front-end. I'd like to make it so that I can drag and drop a file (from the OS) into the program's window. All I need from that is the file's path. From there, the backend will be able to handle things.

Thing is, I don't even know where to begin looking for something like this. I've looked at the examples and the documentation, especially the documentation for the prelude crate. But I get the sense that I'm looking in the wrong places.

I've tried googling, but the most I get is an issue about adding drag-and-drop support to OrbTk, but nothing about how to use it. I don't even know if this works with files that are dragged into the window.

If it's impossible, I could resort to having a browse feature instead of dragging and dropping. (Ideally I will include both, but due to time constraints, I may have to settle on just one.)

If the solution depends on the OS, I'm currently on Windows 10 (but I'd like to make this project work on any OS, if possible). I am not asking for an example of how to do this, but rather I'd like to know where I should look in the documentation for something like this.

**Comment by Autofire** [comment]
Ahhh wait, looks like I found my answer.... `rbtk::api::event::DropFileEvent`

I'm not sure why I didn't search in an event crate until now. Oops... xD

Well, I'll close this, then. I'll open a new issues if I have problems getting things to work.

**Comment by rzerres** [comment]
Hallo Autofire,

thanks for using/ developing your App with OrbTK. Fine that you do find the right crate and source code to keep you going full.

Since we need to document commen workflows, and drag drop is one of the basic functionalities, i'd like to get your feedback once you solved the issue . I'm wrorking on the OrbTK book. Therefore I like to encourage you, to give some feedback. Especially it would be useful, if what you write some documentation inline of your code and Band Jared as the basic for the new upcoming chapter inside the book.

Thanks for your support.
Ralf

Am 19.11.2020 00:59 schrieb Autofire <notifications@github.com>:

Ahhh wait, looks like I found my answer.... rbtk::api::event::DropFileEvent

I'm not sure why I didn't search in an event crate until now. Oops... xD

Well, I'll close this, then. I'll open a new issues if I have problems getting things to work.
