### ISSUE TITLE
[Proposal] Consider replacing dces

### ISSUE THREAD

**Issue by kivimango** [redox-os/orbtk#445]
# Context

Consider replacing the current ECS implementation with a more advanced one OR develop the needed features into dces.

My candidates are:
* specs
* legion

Pro:
* more actively developed
* more contributors than dces
* better documentation and guidelines
* better performance (?)

Con:
* dces has some uniqe features that we already using like property sharing that probably candidates does not have

# Problem description & Solution
dces lacks some features that we might need in 0.4 like parallel execution, entity reusing.
The properties queried by strings.
Probably wastes memory (?): no generations ( if entities deleted betwwen 1 and 10, i think there would be unsued slots in the component store.

**Comment by rongcuid** [comment]
Another good candidate might be `bevy` ecs. It is more like a full game engine right now, but I believe you can depend only on its ECS part. I have used all three of `specs`, `legion`, and `bevy`, and `bevy` has the simplest API.

**Comment by ghost** [comment]
After some experiments with other ECS frameworks, we cannot profit much from their advantages like parallelism. Because an UI toolkit has to many dependencies between different steps like layout calculation and rendering that it's really difficult to do it parallel. 

For now we will continue using DCES. I will also check what I can do to improve it as much as possible. 

For now I will close this issue.
