### ISSUE TITLE
Cannot run on Rust 2021 edition

### ISSUE THREAD

**Issue by wzzc-dev** [redox-os/orbtk#477]
**Describe the bug**
Cannot run on Rust 2021 edition

**To Reproduce**

cargo.toml
```
[package]
name = "ider"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
orbtk = "0.3.1-alpha3"
```

**Expected behavior**

edition = "2018" is successful

**Screenshots**
![image](https://user-images.githubusercontent.com/37931535/150953149-47511bd9-18bf-482d-bf00-eec3ab8034ed.png)

**Desktop (please complete the following information):**
 - OS:  windows 11 

**Additional context**

**Comment by wzzc-dev** [comment]
https://github.com/redox-os/orbtk/pull/459

**Comment by rzerres** [comment]
@OneSeek  just to describe the status ...

The PR is marked WIP, since compiling for target `redox` fails.
This is bound to following facts:

* I don't have an implemented/working redox instance to further test on
* the rustc compiler toolchain on `redox`  is bound to `nightly-2021-06-15`, which obviously does not include the `2021 edition`

Resend a status request to the maintainer (jackpot51). I do know, that they are carefully thinking about the implemented toolchain, since this is quite critical for this rolling microkernel depencencies. 

If your code is build for the other supported distribution targets, you should be fine to apply this PR.

**Comment by wzzc-dev** [comment]
Thank you for reply

**Comment by rzerres** [comment]
The issue is fixed using `develop` branch.
